#!/usr/bin/env python3
"""Extract ASCII-art frames from the M5Stick Buddy species files
(claude-desktop-buddy/src/buddies/*.cpp) and render them as small GIFs for
the menu bar app's species picker. Reuses existing pet designs instead of
re-drawing each one — idle GIF = first pose in doIdle(), pending GIF =
first pose in doAttention()."""

import re
import glob
import os
from PIL import Image, ImageDraw, ImageFont

SRC_DIR = os.path.expanduser(
    "~/Downloads/claude-buddy-project/claude-desktop-buddy/src/buddies")
OUT_DIR = "Sources/ClaudeMenuBarBuddy/Resources"

FONT_SIZE = 14
CHAR_W, CHAR_H = 9, 16  # monospace cell size at this font size

try:
    FONT = ImageFont.truetype("/System/Library/Fonts/Menlo.ttc", FONT_SIZE)
except Exception:
    FONT = ImageFont.load_default()


def first_array_in_function(src: str, func_name: str):
    """Find `static void <func_name>(...) { ... }` and return the first
    `{ "...", "...", ... }` string-literal array inside it."""
    fn_match = re.search(rf"static void {func_name}\([^)]*\)\s*{{", src)
    if not fn_match:
        return None
    start = fn_match.end()
    # crude brace matching to find the end of the function body
    depth = 1
    i = start
    while i < len(src) and depth > 0:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
        i += 1
    body = src[start:i]
    arr_match = re.search(r"\{\s*((?:\"(?:[^\"\\]|\\.)*\"\s*,?\s*)+)\}", body)
    if not arr_match:
        return None
    strings = re.findall(r"\"((?:[^\"\\]|\\.)*)\"", arr_match.group(1))
    return [s.replace('\\\\', '\\') for s in strings]


def render_frame(lines):
    w = max(len(l) for l in lines) * CHAR_W
    h = len(lines) * CHAR_H
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for r, line in enumerate(lines):
        d.text((0, r * CHAR_H), line, font=FONT, fill=(255, 255, 255, 255))
    return img


def render_species(path):
    name = os.path.splitext(os.path.basename(path))[0]
    with open(path) as f:
        src = f.read()

    idle_frame = first_array_in_function(src, "doIdle")
    attn_frame = first_array_in_function(src, "doAttention")
    if not idle_frame or not attn_frame:
        print(f"skip {name}: couldn't extract frames")
        return None

    idle_img = render_frame(idle_frame)
    attn_img = render_frame(attn_frame)

    idle_path = f"{OUT_DIR}/{name}_idle.gif"
    pend_path = f"{OUT_DIR}/{name}_pending.gif"
    idle_img.save(idle_path, save_all=True,
                   append_images=[idle_img], duration=[500, 500], loop=0)
    attn_img.save(pend_path, save_all=True,
                   append_images=[attn_img], duration=[250, 250], loop=0)
    print(f"ok {name}")
    return name


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    names = []
    for path in sorted(glob.glob(f"{SRC_DIR}/*.cpp")):
        n = render_species(path)
        if n:
            names.append(n)
    # Also list the pixel-art panda (already generated by generate_gifs.py)
    if os.path.exists(f"{OUT_DIR}/buddy_idle.gif"):
        names.append("buddy")
    with open(f"{OUT_DIR}/species.txt", "w") as f:
        f.write("\n".join(names))
    print(f"\n{len(names)} species available:", ", ".join(names))
